### ISSUE TITLE
Issue with date format parsing

### ISSUE THREAD

**Issue by kodikos** [Financial-Times/ft-date-format#2]
I was converting the following moment formatter to your library "h:mma Do MMM YYYY". There are 2 problems that I found (after lowercasing YYYY):
1) It doesn't understand mma (which should produce 03am), leaving it as the string mma
2) There is no equivalent for Do (which is day plus ordinal, e.g. 1st)

**Comment by JakeChampion** [comment]
Hi,

There are no plans to add support for these as we have not had a request from an FT Group product to add them.

Do you know if there is an FT Group product wanting this feature? If there is then we would look to add it in 👍

**Comment by kodikos** [comment]
I used to work in the mobile app team, maybe it was something in that? With having not worked there for 3 years, you'll have to excuse me if my memory is a little bad 😄  Hope you're all doing well 👋
