### ISSUE TITLE
Should we remove comma before year?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/ft-date-format#5]
`o-date` includes a comma before the year, e.g. "May 15, 2014 8:10 am", but FT guidelines say to include no comma.
https://github.com/Financial-Times/o-date/blob/v2.11.0/main.js#L6
>FT style for writing dates is June 23 2016 (no commas, month/date/year), August 17, September 12 2012, November 25- December 5 2012, January 2012.

**Comment by chee** [comment]
@notlee i think we should

**Comment by notlee** [comment]
Cool! Somewhere I see the comma is in the byline. It might look a little long without the comma? I'll run by Tim and throw out there in #ft-origami before we make the change

app:
<img width="488" alt="Screenshot 2019-09-17 at 11 01 59" src="https://user-images.githubusercontent.com/10405691/65032254-b173d600-d93a-11e9-9ac2-5b89a8a52502.png">

ft.com:
<img width="553" alt="Screenshot 2019-09-17 at 11 02 42" src="https://user-images.githubusercontent.com/10405691/65032256-b173d600-d93a-11e9-971d-13f8c05d9627.png">
