### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/ft-date-format#6]
Is there any plan to add/support timezone processing? Sample use case:

- server-side code always outputs date in iso-style format
- o-date is supplied with timezone information in the markup alongside the timestamp
- client-side JS detects current timezone (e.g. via `getTimezoneOffset` or similar approach) and adjusts date display, mainly relevant to the X hours ago display

Has something like the above been considered/planned?

**Comment by JakeChampion** [comment]
Hi,

There are no plans to add timezone processing, I'll be closing this issue as we have answered your question.

Do you know if there is an FT Group product wanting this feature? If there is then we would look to add it in 👍

**Comment by petrklus** [comment]
Hi @JakeChampion , thank you for the clarification
